version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  verify-deployment:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_DEFAULT_REGION
      - run:
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition ${MY_APP_PREFIX}-service \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            $BASH_ENV
          name: Get last task definition
      - aws-ecs/verify-revision-is-deployed:
          cluster-name: '${MY_APP_PREFIX}-cluster'
          family: '${MY_APP_PREFIX}-service'
          task-definition-arn: '${TASK_DEFINITION_ARN}'
workflows:
  test-workflow:
    jobs:
      - verify-deployment
