version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:16.14.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm unstall -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths: 
            - ./node_modules
      - run:
          name: dev
          command: npm run dev