version: 2.1
# Workflows are used to partition jobs
orbs: 
  aws-ecs: circleci/aws-ecs@2.2.1
# the version of the yml
workflows:
  # this is one workflow with a job defined
  # you can have more than one of it
  deploy_application:
    
    # jobs are used to perform actions i.e. run instructions
    jobs:
        # This is the name of the job being run
        # You can run more than one job
        # The job accepts the following parameters
        - aws-code-deploy/deploy:
            application-name: $APP_NAME
            bundle-bucket: $BUNDLE_BUCKET
            bundle-key: code/source
            deployment-group: master
            service-role-arn: $ARN
build:
  docker:
    - image: cimg/node:15.6.0
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  steps:
    - checkout
    - node/install-packages # Utilize commands in steps